config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  resources :books #do
  #   member do
  #     get 'buy'
  #     resources :comments
  #   end
  #   collection do
  #     get 'bestof'
  #   end
  # end
  #
  # # Pour les API
  # namespace :api do
  #   namespace :v1 do
  #     get 'version' => 'api#version'
  #   end
  # end
  #
  # # Mettre des contraintes
  # constraints(subdomain:/^admin$/) do
  #   scope module: 'admin' do
  #     resources :books
  #   end
  # end
  #
  # root 'static_pages#home'
  #
  # get 'users/:username' => 'users#show', as: :show_user

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord::Base
  # validates :title, presence: true, length: { minimum: 5 }
  # validates :author, presence: true, length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  # before_filter :set_locale
  #
  # def default_url_options(options={})
  #   logger.debug "default_url-options is passed options: #{options.inspect}\n"
  #   { local: I18n.locale }
  # end
  #
  #  # recupere la langue de la requete http
  # private
  #   def http_header_locale
  #     request.env['HTTP_ACCEPT_LANGUAGE'].scan(/^[a-z]{2}/).first
  #   end
  #
  # def set_locale
  #   I18n.locale = params[:locale] || http_header_locale || I18n.default_locale
  # end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :author)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= simple_form_for(@book) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :author %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<hr />

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= link_to 'Show', book, class: 'btn btn-mini btn-primary' %></td>
        <td><%= link_to 'Edit', edit_book_path(book), class: 'btn btn-mini' %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-mini btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path, class:'btn' %>

app/views/books/new.html.erb
<h1>New Book</h1>
<hr />

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>
<h2><%= @book.title %></h2>
<hr />

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/_header.html.erb
<div class="row">
  <nav class="span12">
    <div class="navbar">
      <div class="navbar-inner">
        <%= link_to 'Book Online', root_path, class: 'brand' %>

        <ul class="nav">
          <li class="divider-vertical"></li>

          <%# Books %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Books</a>
            <ul class="dropdown-menu">
              <li><%= link_to "<i class=\"icon-th-list\"></i>All books".html_safe, books_path %></li>
              <li><%= link_to "<i class=\"icon-plus\"></i> Add".html_safe, new_book_path %></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="row">
    <div class="span12">
      <div class="alert alert-<% key %>"><%= value.html_safe %></div>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Library</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <div class="container" >
    <%= render 'layouts/header' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </div>

  <script type="text/javascript">
    $('alert').delay(5000).fadeOut();
  </script>
  </body>
</html>